language: android
jdk: oraclejdk8

# use trusty beta for JDK 8
sudo: true
dist: trusty

android:
  components:
    - build-tools-21.1.2
    - platform-tools
    - tools
    - android-22
    - sys-img-armeabi-v7a-android-19
    - addon-google_apis-google-19
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support

  licenses:
    - android-sdk-license-bcbbd656
    - android-sdk-license-5be876d5
    - android-sdk-license-598b93a6
    - 'android-*'
    - '.*intel.+'

before_install:
  - export "JAVA8_HOME=/usr/lib/jvm/java-8-oracle"
  - cp xmltemplates/api_keys.xml.template app/src/main/res/values/api_keys.xml
  - mkdir -p app/src/main/res/xml
  - cp xmltemplates/app_tracker.xml.template app/src/main/res/xml/app_tracker.xml

before_script:
  - ulimit -c unlimited -S # increase stack size
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a --skin HVGA
  - sleep 5
  - emulator -avd test -no-skin -no-audio -no-window -no-boot-anim -dpi-device 480 &
  - sleep 10
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - sleep 5 && adb shell input keyevent 82 &

env:
  global:
    - MALLOC_ARENA_MAX=2
    - GRADLE_OPTS='-Dorg.gradle.jvmargs="-Xmx2560m -XX:+HeapDumpOnOutOfMemoryError"'

script:
  - ./gradlew connectedCheck --stacktrace
